import './MainPage.css';
import PlanInputForm from '../components/PlanInputForm';
import { Link } from 'react-router-dom';

export default function MainPage() {
  const result = `This is an example result generated by the OpenAI API.
It can be short or long.
We can show the full text here.`;
    return (
    <div className="pink-background">
        <div className="background-label">
            Weather background
        </div>

        <div>
            <Link to="/results">Go to Result Page</Link>
        </div>

        <div className="openai-result-box">
            {result}
        </div>

        <div className="plan-input-area">
            <PlanInputForm />
        </div>
    </div>
  );
}