import './ResultPage.css';

export default function ResultPage({ openAIResult }) {
  const result = openAIResult || `This is an example result generated by the OpenAI API.
It can be short or long.
We can show the full text here`;
  return (
    <div className="light-blue-background">
        <div className="background-label">
            Weather background
        </div>

        <div className="saved-plans-container">
          <h2>
            Saved OpenAI Plans
          </h2>
          <div className="saved-plans-box1">
            {result}
          </div>
        </div>

        <div className="suggest-plans-container">
          <h2>
            sugguested OpenAI Plans
          </h2>
          <div className="suggest-plans-box1">
            {result}
          </div>
        </div>
    </div>
  );
}